/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountChangedWebhookData {
    /// New account id
    #[serde(rename = "accountId")]
    pub account_id: f64,
}

impl AccountChangedWebhookData {
    pub fn new(account_id: f64) -> AccountChangedWebhookData {
        AccountChangedWebhookData {
            account_id,
        }
    }
}

