/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyDto {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl ApiKeyDto {
    pub fn new(key: String, secret: String) -> ApiKeyDto {
        ApiKeyDto {
            key,
            secret,
        }
    }
}

