/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLnurlStatusResponseDto {
    #[serde(rename = "isComplete")]
    pub is_complete: bool,
    #[serde(rename = "accessToken", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
}

impl AuthLnurlStatusResponseDto {
    pub fn new(is_complete: bool) -> AuthLnurlStatusResponseDto {
        AuthLnurlStatusResponseDto {
            is_complete,
            access_token: None,
        }
    }
}

