/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankAccountDto {
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "iban")]
    pub iban: String,
    #[serde(rename = "preferredCurrency", skip_serializing_if = "Option::is_none")]
    pub preferred_currency: Option<Box<models::FiatDto>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "default")]
    pub default: bool,
    #[serde(rename = "active")]
    pub active: bool,
}

impl BankAccountDto {
    pub fn new(id: f64, iban: String, default: bool, active: bool) -> BankAccountDto {
        BankAccountDto {
            id,
            iban,
            preferred_currency: None,
            label: None,
            default,
            active,
        }
    }
}

