/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyHistoryEntryDto {
    /// Entry timestamp
    #[serde(rename = "date")]
    pub date: String,
    /// Fiat values
    #[serde(rename = "value")]
    pub value: Box<models::CustodyFiatValueDto>,
}

impl CustodyHistoryEntryDto {
    pub fn new(date: String, value: models::CustodyFiatValueDto) -> CustodyHistoryEntryDto {
        CustodyHistoryEntryDto {
            date,
            value: Box::new(value),
        }
    }
}

