/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyOrderResponseDto {
    /// Transaction order ID
    #[serde(rename = "id")]
    pub id: f64,
    /// UID of the transaction order
    #[serde(rename = "uid")]
    pub uid: String,
    /// Price timestamp
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    /// Minimum volume in source asset
    #[serde(rename = "minVolume")]
    pub min_volume: f64,
    /// Maximum Volume in source asset
    #[serde(rename = "maxVolume")]
    pub max_volume: f64,
    /// Amount in source asset
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Source asset name, Asset or Fiat
    #[serde(rename = "sourceAsset")]
    pub source_asset: String,
    /// Target asset name, Asset or Fiat
    #[serde(rename = "targetAsset")]
    pub target_asset: String,
    /// Fee infos in source asset
    #[serde(rename = "fees")]
    pub fees: Box<models::FeeDto>,
    /// Fee infos in target asset
    #[serde(rename = "feesTarget")]
    pub fees_target: Box<models::FeeDto>,
    /// Minimum volume in target asset
    #[serde(rename = "minVolumeTarget")]
    pub min_volume_target: f64,
    /// Maximum volume in target asset
    #[serde(rename = "maxVolumeTarget")]
    pub max_volume_target: f64,
    /// Exchange rate in source/target
    #[serde(rename = "exchangeRate")]
    pub exchange_rate: f64,
    /// Final rate (incl. fees) in source/target
    #[serde(rename = "rate")]
    pub rate: f64,
    #[serde(rename = "priceSteps")]
    pub price_steps: Vec<models::PriceStep>,
    /// Estimated amount in target asset
    #[serde(rename = "estimatedAmount")]
    pub estimated_amount: f64,
    /// Payment request (e.g. Lightning invoice)
    #[serde(rename = "paymentRequest", skip_serializing_if = "Option::is_none")]
    pub payment_request: Option<String>,
    #[serde(rename = "isValid")]
    pub is_valid: bool,
    /// Error message in case isValid is false
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Error>,
    /// Bank transaction beneficiary
    #[serde(rename = "beneficiary", skip_serializing_if = "Option::is_none")]
    pub beneficiary: Option<Box<models::BeneficiaryDto>>,
    /// Infos for Buy Custody Orders
    #[serde(rename = "buyInfos", skip_serializing_if = "Option::is_none")]
    pub buy_infos: Option<Box<models::CustodyOrderBuyResponseDto>>,
}

impl CustodyOrderResponseDto {
    pub fn new(id: f64, uid: String, timestamp: String, min_volume: f64, max_volume: f64, amount: f64, source_asset: String, target_asset: String, fees: models::FeeDto, fees_target: models::FeeDto, min_volume_target: f64, max_volume_target: f64, exchange_rate: f64, rate: f64, price_steps: Vec<models::PriceStep>, estimated_amount: f64, is_valid: bool) -> CustodyOrderResponseDto {
        CustodyOrderResponseDto {
            id,
            uid,
            timestamp,
            min_volume,
            max_volume,
            amount,
            source_asset,
            target_asset,
            fees: Box::new(fees),
            fees_target: Box::new(fees_target),
            min_volume_target,
            max_volume_target,
            exchange_rate,
            rate,
            price_steps,
            estimated_amount,
            payment_request: None,
            is_valid,
            error: None,
            beneficiary: None,
            buy_infos: None,
        }
    }
}
/// Error message in case isValid is false
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "AmountTooLow")]
    AmountTooLow,
    #[serde(rename = "AmountTooHigh")]
    AmountTooHigh,
    #[serde(rename = "BankTransactionMissing")]
    BankTransactionMissing,
    #[serde(rename = "KycRequired")]
    KycRequired,
    #[serde(rename = "KycDataRequired")]
    KycDataRequired,
    #[serde(rename = "KycRequiredInstant")]
    KycRequiredInstant,
    #[serde(rename = "LimitExceeded")]
    LimitExceeded,
    #[serde(rename = "NationalityNotAllowed")]
    NationalityNotAllowed,
    #[serde(rename = "NameRequired")]
    NameRequired,
    #[serde(rename = "VideoIdentRequired")]
    VideoIdentRequired,
}

impl Default for Error {
    fn default() -> Error {
        Self::AmountTooLow
    }
}

