/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyAssetBalanceDto {
    /// Asset
    #[serde(rename = "asset")]
    pub asset: Box<models::CustodyAssetDto>,
    /// Balance in asset
    #[serde(rename = "balance")]
    pub balance: f64,
    /// Balances in fiat values
    #[serde(rename = "value")]
    pub value: Box<models::CustodyFiatValueDto>,
}

impl CustodyAssetBalanceDto {
    pub fn new(asset: models::CustodyAssetDto, balance: f64, value: models::CustodyFiatValueDto) -> CustodyAssetBalanceDto {
        CustodyAssetBalanceDto {
            asset: Box::new(asset),
            balance,
            value: Box::new(value),
        }
    }
}

