/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBuyQuoteDto {
    /// Source currency
    #[serde(rename = "currency")]
    pub currency: Box<models::EntityDto>,
    /// Target asset
    #[serde(rename = "asset")]
    pub asset: Box<models::EntityDto>,
    /// Amount in source currency
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Amount in target asset
    #[serde(rename = "targetAmount", skip_serializing_if = "Option::is_none")]
    pub target_amount: Option<f64>,
    /// Payment method
    #[serde(rename = "paymentMethod", skip_serializing_if = "Option::is_none")]
    pub payment_method: Option<PaymentMethod>,
    /// This field is deprecated, use \"specialCode\" instead.
    #[serde(rename = "discountCode", skip_serializing_if = "Option::is_none")]
    pub discount_code: Option<String>,
    /// Special code
    #[serde(rename = "specialCode", skip_serializing_if = "Option::is_none")]
    pub special_code: Option<String>,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<String>,
}

impl GetBuyQuoteDto {
    pub fn new(currency: models::EntityDto, asset: models::EntityDto) -> GetBuyQuoteDto {
        GetBuyQuoteDto {
            currency: Box::new(currency),
            asset: Box::new(asset),
            amount: None,
            target_amount: None,
            payment_method: None,
            discount_code: None,
            special_code: None,
            wallet: None,
        }
    }
}
/// Payment method
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PaymentMethod {
    #[serde(rename = "Bank")]
    Bank,
    #[serde(rename = "Instant")]
    Instant,
    #[serde(rename = "Card")]
    Card,
}

impl Default for PaymentMethod {
    fn default() -> PaymentMethod {
        Self::Bank
    }
}

