/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycSignatoryPowerData {
    #[serde(rename = "signatoryPower")]
    pub signatory_power: SignatoryPower,
}

impl KycSignatoryPowerData {
    pub fn new(signatory_power: SignatoryPower) -> KycSignatoryPowerData {
        KycSignatoryPowerData {
            signatory_power,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SignatoryPower {
    #[serde(rename = "Single")]
    Single,
    #[serde(rename = "Double")]
    Double,
    #[serde(rename = "None")]
    None,
}

impl Default for SignatoryPower {
    fn default() -> SignatoryPower {
        Self::Single
    }
}

