/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycFinancialResponse {
    /// Question key
    #[serde(rename = "key")]
    pub key: String,
    /// Response value (option key(s) or plain text)
    #[serde(rename = "value")]
    pub value: String,
}

impl KycFinancialResponse {
    pub fn new(key: String, value: String) -> KycFinancialResponse {
        KycFinancialResponse {
            key,
            value,
        }
    }
}

