/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycFinancialOption {
    /// Option key
    #[serde(rename = "key")]
    pub key: String,
    /// Option text (translated)
    #[serde(rename = "text")]
    pub text: String,
}

impl KycFinancialOption {
    pub fn new(key: String, text: String) -> KycFinancialOption {
        KycFinancialOption {
            key,
            text,
        }
    }
}

