/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LanguageDto {
    #[serde(rename = "id")]
    pub id: f64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "foreignName")]
    pub foreign_name: String,
    #[serde(rename = "enable")]
    pub enable: bool,
}

impl LanguageDto {
    pub fn new(id: f64, name: String, symbol: String, foreign_name: String, enable: bool) -> LanguageDto {
        LanguageDto {
            id,
            name,
            symbol,
            foreign_name,
            enable,
        }
    }
}

