/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinAmount {
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "asset")]
    pub asset: String,
}

impl MinAmount {
    pub fn new(amount: f64, asset: String) -> MinAmount {
        MinAmount {
            amount,
            asset,
        }
    }
}

