/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentDataDto {
    #[serde(rename = "purpose")]
    pub purpose: String,
    #[serde(rename = "contractAccepted")]
    pub contract_accepted: bool,
}

impl PaymentDataDto {
    pub fn new(purpose: String, contract_accepted: bool) -> PaymentDataDto {
        PaymentDataDto {
            purpose,
            contract_accepted,
        }
    }
}

