/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdfDto {
    /// Base64 encoded PDF
    #[serde(rename = "pdfData")]
    pub pdf_data: String,
}

impl PdfDto {
    pub fn new(pdf_data: String) -> PdfDto {
        PdfDto {
            pdf_data,
        }
    }
}

