/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceStep {
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl PriceStep {
    pub fn new(source: String, from: String, to: String, price: f64, timestamp: String) -> PriceStep {
        PriceStep {
            source,
            from,
            to,
            price,
            timestamp,
        }
    }
}

