/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwapQuoteDto {
    /// Fee amount in source asset
    #[serde(rename = "feeAmount")]
    pub fee_amount: f64,
    /// Amount in source asset
    #[serde(rename = "amount")]
    pub amount: f64,
    /// Exchange rate in source/target
    #[serde(rename = "exchangeRate")]
    pub exchange_rate: f64,
    /// Estimated amount in target asset
    #[serde(rename = "estimatedAmount")]
    pub estimated_amount: f64,
    /// Minimum volume in source asset
    #[serde(rename = "minVolume")]
    pub min_volume: f64,
    /// Maximum volume in source asset
    #[serde(rename = "maxVolume")]
    pub max_volume: f64,
    /// Fee infos in source asset
    #[serde(rename = "fees")]
    pub fees: Box<models::FeeDto>,
    /// Fee infos in target asset
    #[serde(rename = "feesTarget")]
    pub fees_target: Box<models::FeeDto>,
    /// Minimum volume in target asset
    #[serde(rename = "minVolumeTarget")]
    pub min_volume_target: f64,
    /// Maximum volume in target asset
    #[serde(rename = "maxVolumeTarget")]
    pub max_volume_target: f64,
    #[serde(rename = "priceSteps")]
    pub price_steps: Vec<models::PriceStep>,
    #[serde(rename = "isValid")]
    pub is_valid: bool,
    /// Error message in case isValid is false
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Error>,
}

impl SwapQuoteDto {
    pub fn new(fee_amount: f64, amount: f64, exchange_rate: f64, estimated_amount: f64, min_volume: f64, max_volume: f64, fees: models::FeeDto, fees_target: models::FeeDto, min_volume_target: f64, max_volume_target: f64, price_steps: Vec<models::PriceStep>, is_valid: bool) -> SwapQuoteDto {
        SwapQuoteDto {
            fee_amount,
            amount,
            exchange_rate,
            estimated_amount,
            min_volume,
            max_volume,
            fees: Box::new(fees),
            fees_target: Box::new(fees_target),
            min_volume_target,
            max_volume_target,
            price_steps,
            is_valid,
            error: None,
        }
    }
}
/// Error message in case isValid is false
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Error {
    #[serde(rename = "AmountTooLow")]
    AmountTooLow,
    #[serde(rename = "AmountTooHigh")]
    AmountTooHigh,
    #[serde(rename = "BankTransactionMissing")]
    BankTransactionMissing,
    #[serde(rename = "KycRequired")]
    KycRequired,
    #[serde(rename = "KycDataRequired")]
    KycDataRequired,
    #[serde(rename = "KycRequiredInstant")]
    KycRequiredInstant,
    #[serde(rename = "LimitExceeded")]
    LimitExceeded,
    #[serde(rename = "NationalityNotAllowed")]
    NationalityNotAllowed,
    #[serde(rename = "NameRequired")]
    NameRequired,
    #[serde(rename = "VideoIdentRequired")]
    VideoIdentRequired,
}

impl Default for Error {
    fn default() -> Error {
        Self::AmountTooLow
    }
}

