/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionRefundDto {
    /// Refund address or refund IBAN
    #[serde(rename = "refundTarget")]
    pub refund_target: String,
}

impl TransactionRefundDto {
    pub fn new(refund_target: String) -> TransactionRefundDto {
        TransactionRefundDto {
            refund_target,
        }
    }
}

