/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateBankAccountDto {
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "preferredCurrency", skip_serializing_if = "Option::is_none")]
    pub preferred_currency: Option<Box<models::EntityDto>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
}

impl UpdateBankAccountDto {
    pub fn new() -> UpdateBankAccountDto {
        UpdateBankAccountDto {
            label: None,
            preferred_currency: None,
            active: None,
            default: None,
        }
    }
}

