/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolumeLimitDto {
    /// Minimum transaction volume (in fiat)
    #[serde(rename = "minVolume")]
    pub min_volume: f64,
    /// Maximum transaction volume (in fiat)
    #[serde(rename = "maxVolume")]
    pub max_volume: f64,
}

impl VolumeLimitDto {
    pub fn new(min_volume: f64, max_volume: f64) -> VolumeLimitDto {
        VolumeLimitDto {
            min_volume,
            max_volume,
        }
    }
}

