/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VolumesDto {
    /// Total buy volume in CHF
    #[serde(rename = "buy")]
    pub buy: Box<models::VolumeInformation>,
    /// Total sell volume in CHF
    #[serde(rename = "sell")]
    pub sell: Box<models::VolumeInformation>,
    /// Total swap volume in CHF
    #[serde(rename = "swap")]
    pub swap: Box<models::VolumeInformation>,
}

impl VolumesDto {
    pub fn new(buy: models::VolumeInformation, sell: models::VolumeInformation, swap: models::VolumeInformation) -> VolumesDto {
        VolumesDto {
            buy: Box::new(buy),
            sell: Box::new(sell),
            swap: Box::new(swap),
        }
    }
}

