/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthLnurlCreateLoginResponseDto {
    #[serde(rename = "k1")]
    pub k1: String,
    #[serde(rename = "lnurl")]
    pub lnurl: String,
}

impl AuthLnurlCreateLoginResponseDto {
    pub fn new(k1: String, lnurl: String) -> AuthLnurlCreateLoginResponseDto {
        AuthLnurlCreateLoginResponseDto {
            k1,
            lnurl,
        }
    }
}

