/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyOrderBuyResponseDto {
    #[serde(rename = "remittanceInfo", skip_serializing_if = "Option::is_none")]
    pub remittance_info: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "bank", skip_serializing_if = "Option::is_none")]
    pub bank: Option<String>,
    #[serde(rename = "street", skip_serializing_if = "Option::is_none")]
    pub street: Option<String>,
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    #[serde(rename = "zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "iban", skip_serializing_if = "Option::is_none")]
    pub iban: Option<String>,
    #[serde(rename = "bic", skip_serializing_if = "Option::is_none")]
    pub bic: Option<String>,
    #[serde(rename = "sepaInstant", skip_serializing_if = "Option::is_none")]
    pub sepa_instant: Option<bool>,
}

impl CustodyOrderBuyResponseDto {
    pub fn new() -> CustodyOrderBuyResponseDto {
        CustodyOrderBuyResponseDto {
            remittance_info: None,
            name: None,
            bank: None,
            street: None,
            number: None,
            zip: None,
            city: None,
            country: None,
            iban: None,
            bic: None,
            sepa_instant: None,
        }
    }
}

