/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyHistoryDto {
    /// Total value history
    #[serde(rename = "totalValue")]
    pub total_value: Vec<models::CustodyHistoryEntryDto>,
}

impl CustodyHistoryDto {
    pub fn new(total_value: Vec<models::CustodyHistoryEntryDto>) -> CustodyHistoryDto {
        CustodyHistoryDto {
            total_value,
        }
    }
}

