/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyBalanceDto {
    /// Total balance in fiat values
    #[serde(rename = "totalValue")]
    pub total_value: Box<models::CustodyFiatValueDto>,
    /// Asset balances
    #[serde(rename = "balances")]
    pub balances: Vec<models::CustodyAssetBalanceDto>,
}

impl CustodyBalanceDto {
    pub fn new(total_value: models::CustodyFiatValueDto, balances: Vec<models::CustodyAssetBalanceDto>) -> CustodyBalanceDto {
        CustodyBalanceDto {
            total_value: Box::new(total_value),
            balances,
        }
    }
}

