/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodyOrderDto {
    /// Type of your requested order
    #[serde(rename = "type")]
    pub r#type: String,
    /// ID of your order
    #[serde(rename = "orderId")]
    pub order_id: f64,
    /// Type of your requested order
    #[serde(rename = "status")]
    pub status: String,
    /// Payment info of your requested order
    #[serde(rename = "paymentInfo")]
    pub payment_info: Box<models::CustodyOrderResponseDto>,
}

impl CustodyOrderDto {
    pub fn new(r#type: String, order_id: f64, status: String, payment_info: models::CustodyOrderResponseDto) -> CustodyOrderDto {
        CustodyOrderDto {
            r#type,
            order_id,
            status,
            payment_info: Box::new(payment_info),
        }
    }
}

