/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBuyPaymentInfoDto {
    #[serde(rename = "iban", skip_serializing_if = "Option::is_none")]
    pub iban: Option<String>,
    /// Source currency
    #[serde(rename = "currency")]
    pub currency: Box<models::EntityDto>,
    /// Target asset
    #[serde(rename = "asset")]
    pub asset: Box<models::EntityDto>,
    /// Amount in source currency
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Amount in target asset
    #[serde(rename = "targetAmount", skip_serializing_if = "Option::is_none")]
    pub target_amount: Option<f64>,
    /// Custom transaction id
    #[serde(rename = "externalTransactionId", skip_serializing_if = "Option::is_none")]
    pub external_transaction_id: Option<String>,
    /// Require an exact price (may take longer)
    #[serde(rename = "exactPrice", skip_serializing_if = "Option::is_none")]
    pub exact_price: Option<bool>,
}

impl GetBuyPaymentInfoDto {
    pub fn new(currency: models::EntityDto, asset: models::EntityDto) -> GetBuyPaymentInfoDto {
        GetBuyPaymentInfoDto {
            iban: None,
            currency: Box::new(currency),
            asset: Box::new(asset),
            amount: None,
            target_amount: None,
            external_transaction_id: None,
            exact_price: None,
        }
    }
}

