/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSwapPaymentInfoDto {
    /// Source asset
    #[serde(rename = "sourceAsset")]
    pub source_asset: Box<models::EntityDto>,
    /// Amount in source asset
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Target asset
    #[serde(rename = "targetAsset")]
    pub target_asset: Box<models::EntityDto>,
    /// Amount in target asset
    #[serde(rename = "targetAmount", skip_serializing_if = "Option::is_none")]
    pub target_amount: Option<f64>,
    /// Custom transaction id
    #[serde(rename = "externalTransactionId", skip_serializing_if = "Option::is_none")]
    pub external_transaction_id: Option<String>,
    /// Require an exact price (may take longer)
    #[serde(rename = "exactPrice", skip_serializing_if = "Option::is_none")]
    pub exact_price: Option<bool>,
}

impl GetSwapPaymentInfoDto {
    pub fn new(source_asset: models::EntityDto, target_asset: models::EntityDto) -> GetSwapPaymentInfoDto {
        GetSwapPaymentInfoDto {
            source_asset: Box::new(source_asset),
            amount: None,
            target_asset: Box::new(target_asset),
            target_amount: None,
            external_transaction_id: None,
            exact_price: None,
        }
    }
}

