/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSellPaymentInfoDto {
    #[serde(rename = "iban")]
    pub iban: String,
    /// Source asset
    #[serde(rename = "asset")]
    pub asset: Box<models::EntityDto>,
    /// Target currency
    #[serde(rename = "currency")]
    pub currency: Box<models::EntityDto>,
    /// Amount in source asset
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Amount in target currency
    #[serde(rename = "targetAmount", skip_serializing_if = "Option::is_none")]
    pub target_amount: Option<f64>,
    /// Custom transaction id
    #[serde(rename = "externalTransactionId", skip_serializing_if = "Option::is_none")]
    pub external_transaction_id: Option<String>,
    /// Require an exact price (may take longer)
    #[serde(rename = "exactPrice", skip_serializing_if = "Option::is_none")]
    pub exact_price: Option<bool>,
}

impl GetSellPaymentInfoDto {
    pub fn new(iban: String, asset: models::EntityDto, currency: models::EntityDto) -> GetSellPaymentInfoDto {
        GetSellPaymentInfoDto {
            iban,
            asset: Box::new(asset),
            currency: Box::new(currency),
            amount: None,
            target_amount: None,
            external_transaction_id: None,
            exact_price: None,
        }
    }
}

