/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSwapQuoteDto {
    /// Source asset
    #[serde(rename = "sourceAsset")]
    pub source_asset: Box<models::EntityDto>,
    /// Amount in source asset
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// Target asset
    #[serde(rename = "targetAsset")]
    pub target_asset: Box<models::EntityDto>,
    /// Amount in target asset
    #[serde(rename = "targetAmount", skip_serializing_if = "Option::is_none")]
    pub target_amount: Option<f64>,
    /// This field is deprecated, use \"specialCode\" instead.
    #[serde(rename = "discountCode", skip_serializing_if = "Option::is_none")]
    pub discount_code: Option<String>,
    /// Special code
    #[serde(rename = "specialCode", skip_serializing_if = "Option::is_none")]
    pub special_code: Option<String>,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<String>,
}

impl GetSwapQuoteDto {
    pub fn new(source_asset: models::EntityDto, target_asset: models::EntityDto) -> GetSwapQuoteDto {
        GetSwapQuoteDto {
            source_asset: Box::new(source_asset),
            amount: None,
            target_asset: Box::new(target_asset),
            target_amount: None,
            discount_code: None,
            special_code: None,
            wallet: None,
        }
    }
}

