/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycFinancialInData {
    #[serde(rename = "responses")]
    pub responses: Vec<models::KycFinancialResponse>,
}

impl KycFinancialInData {
    pub fn new(responses: Vec<models::KycFinancialResponse>) -> KycFinancialInData {
        KycFinancialInData {
            responses,
        }
    }
}

