/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycFinancialOutData {
    #[serde(rename = "responses")]
    pub responses: Vec<models::KycFinancialResponse>,
    #[serde(rename = "questions")]
    pub questions: Vec<models::KycFinancialQuestion>,
}

impl KycFinancialOutData {
    pub fn new(responses: Vec<models::KycFinancialResponse>, questions: Vec<models::KycFinancialQuestion>) -> KycFinancialOutData {
        KycFinancialOutData {
            responses,
            questions,
        }
    }
}

