/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycReportDto {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "contentType")]
    pub content_type: String,
}

impl KycReportDto {
    pub fn new(r#type: Type, content_type: String) -> KycReportDto {
        KycReportDto {
            r#type,
            content_type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Identification")]
    Identification,
}

impl Default for Type {
    fn default() -> Type {
        Self::Identification
    }
}

