/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycSessionDto {
    #[serde(rename = "kycLevel")]
    pub kyc_level: KycLevel,
    #[serde(rename = "tradingLimit")]
    pub trading_limit: Box<models::TradingLimit>,
    /// Connected KYC clients
    #[serde(rename = "kycClients")]
    pub kyc_clients: Vec<Vec<String>>,
    #[serde(rename = "language")]
    pub language: Box<models::LanguageDto>,
    #[serde(rename = "kycSteps")]
    pub kyc_steps: Vec<models::KycStepDto>,
    #[serde(rename = "currentStep", skip_serializing_if = "Option::is_none")]
    pub current_step: Option<Box<models::KycStepSessionDto>>,
}

impl KycSessionDto {
    pub fn new(kyc_level: KycLevel, trading_limit: models::TradingLimit, kyc_clients: Vec<Vec<String>>, language: models::LanguageDto, kyc_steps: Vec<models::KycStepDto>) -> KycSessionDto {
        KycSessionDto {
            kyc_level,
            trading_limit: Box::new(trading_limit),
            kyc_clients,
            language: Box::new(language),
            kyc_steps,
            current_step: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KycLevel {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "10")]
    Variant10,
    #[serde(rename = "20")]
    Variant20,
    #[serde(rename = "30")]
    Variant30,
    #[serde(rename = "40")]
    Variant40,
    #[serde(rename = "50")]
    Variant50,
    #[serde(rename = "-10")]
    Variant102,
    #[serde(rename = "-20")]
    Variant202,
}

impl Default for KycLevel {
    fn default() -> KycLevel {
        Self::Variant0
    }
}

