/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycOperationalData {
    /// Is the organization operationally active?
    #[serde(rename = "isOperational")]
    pub is_operational: bool,
    /// Organization Website URL
    #[serde(rename = "websiteUrl", skip_serializing_if = "Option::is_none")]
    pub website_url: Option<String>,
}

impl KycOperationalData {
    pub fn new(is_operational: bool) -> KycOperationalData {
        KycOperationalData {
            is_operational,
            website_url: None,
        }
    }
}

