/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KycDataDto {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kycStatus")]
    pub kyc_status: KycStatus,
    #[serde(rename = "kycHash")]
    pub kyc_hash: String,
}

impl KycDataDto {
    pub fn new(id: String, kyc_status: KycStatus, kyc_hash: String) -> KycDataDto {
        KycDataDto {
            id,
            kyc_status,
            kyc_hash,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KycStatus {
    #[serde(rename = "NA")]
    Na,
    #[serde(rename = "Light")]
    Light,
    #[serde(rename = "Full")]
    Full,
    #[serde(rename = "Rejected")]
    Rejected,
}

impl Default for KycStatus {
    fn default() -> KycStatus {
        Self::Na
    }
}

