/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LimitRequestDto {
    #[serde(rename = "limit")]
    pub limit: f64,
    #[serde(rename = "investmentDate")]
    pub investment_date: InvestmentDate,
    #[serde(rename = "fundOrigin")]
    pub fund_origin: FundOrigin,
    #[serde(rename = "fundOriginText", skip_serializing_if = "Option::is_none")]
    pub fund_origin_text: Option<String>,
}

impl LimitRequestDto {
    pub fn new(limit: f64, investment_date: InvestmentDate, fund_origin: FundOrigin) -> LimitRequestDto {
        LimitRequestDto {
            limit,
            investment_date,
            fund_origin,
            fund_origin_text: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InvestmentDate {
    #[serde(rename = "Now")]
    Now,
    #[serde(rename = "Future")]
    Future,
}

impl Default for InvestmentDate {
    fn default() -> InvestmentDate {
        Self::Now
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FundOrigin {
    #[serde(rename = "Savings")]
    Savings,
    #[serde(rename = "BusinessProfits")]
    BusinessProfits,
    #[serde(rename = "StockGains")]
    StockGains,
    #[serde(rename = "CryptoGains")]
    CryptoGains,
    #[serde(rename = "Inheritance")]
    Inheritance,
    #[serde(rename = "Other")]
    Other,
}

impl Default for FundOrigin {
    fn default() -> FundOrigin {
        Self::Savings
    }
}

