/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkedUserInDto {
    #[serde(rename = "address")]
    pub address: String,
}

impl LinkedUserInDto {
    pub fn new(address: String) -> LinkedUserInDto {
        LinkedUserInDto {
            address,
        }
    }
}

