/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PermitDto {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "signatureTransferContract")]
    pub signature_transfer_contract: String,
    #[serde(rename = "permittedAmount")]
    pub permitted_amount: f64,
    #[serde(rename = "executorAddress")]
    pub executor_address: String,
    #[serde(rename = "nonce")]
    pub nonce: f64,
    #[serde(rename = "deadline")]
    pub deadline: String,
}

impl PermitDto {
    pub fn new(address: String, signature: String, signature_transfer_contract: String, permitted_amount: f64, executor_address: String, nonce: f64, deadline: String) -> PermitDto {
        PermitDto {
            address,
            signature,
            signature_transfer_contract,
            permitted_amount,
            executor_address,
            nonce,
            deadline,
        }
    }
}

