/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReferralDto {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Referral commission factor
    #[serde(rename = "commission")]
    pub commission: f64,
    /// Referral volume in EUR
    #[serde(rename = "volume")]
    pub volume: f64,
    /// Referral credit in EUR
    #[serde(rename = "credit")]
    pub credit: f64,
    /// Paid referral credit in EUR
    #[serde(rename = "paidCredit")]
    pub paid_credit: f64,
    /// Number of users referred
    #[serde(rename = "userCount")]
    pub user_count: f64,
    /// Number of active users referred
    #[serde(rename = "activeUserCount")]
    pub active_user_count: f64,
}

impl ReferralDto {
    pub fn new(commission: f64, volume: f64, credit: f64, paid_credit: f64, user_count: f64, active_user_count: f64) -> ReferralDto {
        ReferralDto {
            code: None,
            commission,
            volume,
            credit,
            paid_credit,
            user_count,
            active_user_count,
        }
    }
}

