/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Setup2faDto {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

impl Setup2faDto {
    pub fn new(r#type: Type) -> Setup2faDto {
        Setup2faDto {
            r#type,
            secret: None,
            uri: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "App")]
    App,
    #[serde(rename = "Mail")]
    Mail,
}

impl Default for Type {
    fn default() -> Type {
        Self::App
    }
}

