/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignUpDto {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// This field is deprecated, use \"specialCode\" instead.
    #[serde(rename = "discountCode", skip_serializing_if = "Option::is_none")]
    pub discount_code: Option<String>,
    /// Special code
    #[serde(rename = "specialCode", skip_serializing_if = "Option::is_none")]
    pub special_code: Option<String>,
    /// Moderator
    #[serde(rename = "moderator", skip_serializing_if = "Option::is_none")]
    pub moderator: Option<String>,
    /// IP region filter
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<serde_json::Value>,
    #[serde(rename = "usedRef", skip_serializing_if = "Option::is_none")]
    pub used_ref: Option<String>,
    #[serde(rename = "wallet", skip_serializing_if = "Option::is_none")]
    pub wallet: Option<String>,
}

impl SignUpDto {
    pub fn new(address: String, signature: String) -> SignUpDto {
        SignUpDto {
            address,
            signature,
            key: None,
            discount_code: None,
            special_code: None,
            moderator: None,
            region: None,
            used_ref: None,
            wallet: None,
        }
    }
}

