/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradingLimit {
    /// Trading limit in CHF
    #[serde(rename = "limit")]
    pub limit: f64,
    /// Remaining limit (only available for yearly limits)
    #[serde(rename = "remaining", skip_serializing_if = "Option::is_none")]
    pub remaining: Option<f64>,
    #[serde(rename = "period")]
    pub period: String,
}

impl TradingLimit {
    pub fn new(limit: f64, period: String) -> TradingLimit {
        TradingLimit {
            limit,
            remaining: None,
            period,
        }
    }
}

