/*
 * DFX API
 *
 * DFX API PRD (updated on 7/3/2025, 12:42:13 PM)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAddressDto {
    #[serde(rename = "wallet")]
    pub wallet: String,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "explorerUrl", skip_serializing_if = "Option::is_none")]
    pub explorer_url: Option<String>,
    #[serde(rename = "blockchains")]
    pub blockchains: Vec<Blockchains>,
    #[serde(rename = "volumes")]
    pub volumes: Box<models::VolumesDto>,
    #[serde(rename = "refCode", skip_serializing_if = "Option::is_none")]
    pub ref_code: Option<String>,
    #[serde(rename = "apiKeyCT", skip_serializing_if = "Option::is_none")]
    pub api_key_ct: Option<String>,
    #[serde(rename = "apiFilterCT", skip_serializing_if = "Option::is_none")]
    pub api_filter_ct: Option<Vec<String>>,
    #[serde(rename = "isCustody")]
    pub is_custody: bool,
}

impl UserAddressDto {
    pub fn new(wallet: String, address: String, blockchains: Vec<Blockchains>, volumes: models::VolumesDto, is_custody: bool) -> UserAddressDto {
        UserAddressDto {
            wallet,
            label: None,
            address,
            explorer_url: None,
            blockchains,
            volumes: Box::new(volumes),
            ref_code: None,
            api_key_ct: None,
            api_filter_ct: None,
            is_custody,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Blockchains {
    #[serde(rename = "Bitcoin")]
    Bitcoin,
    #[serde(rename = "Lightning")]
    Lightning,
    #[serde(rename = "Monero")]
    Monero,
    #[serde(rename = "Ethereum")]
    Ethereum,
    #[serde(rename = "BinanceSmartChain")]
    BinanceSmartChain,
    #[serde(rename = "Optimism")]
    Optimism,
    #[serde(rename = "Arbitrum")]
    Arbitrum,
    #[serde(rename = "Polygon")]
    Polygon,
    #[serde(rename = "Base")]
    Base,
    #[serde(rename = "Haqq")]
    Haqq,
    #[serde(rename = "Liquid")]
    Liquid,
    #[serde(rename = "Arweave")]
    Arweave,
    #[serde(rename = "Cardano")]
    Cardano,
    #[serde(rename = "DeFiChain")]
    DeFiChain,
    #[serde(rename = "Railgun")]
    Railgun,
    #[serde(rename = "BinancePay")]
    BinancePay,
    #[serde(rename = "Solana")]
    Solana,
    #[serde(rename = "Gnosis")]
    Gnosis,
}

impl Default for Blockchains {
    fn default() -> Blockchains {
        Self::Bitcoin
    }
}

